### PR TITLE
Fix incorrect RestClient encoding

### LINKED ISSUE #285: Fix secrets cuke encoding issue
One of our secrets cukes that deals with binary data is attempting to compare a UTF-8 encoded binary string with an ASCII-8BIT encoded string. This comparison fails, even though they have identical byte values.

### PR DESCRIPTION
**Pull request by jtuttle**
Closes #285

### CODE REVIEW

File: cucumber/api/features/step_definitions/response_steps.rb [hunk 1]
```diff
@@ -53,5 +53,5 @@
 Then(/^the binary result is preserved$/) do
   expect(@result).to be
   expect(@result.headers[:content_type]).to include("application/octet-stream")
```
Comment (apotterri) [inline cucumber/api/features/step_definitions/response_steps.rb]: Can we check to make sure `content_type` is exactly `application/octet-stream`, here and in the step above? It shouldn't ever be anything else, but let's not give RestClient the chance to muck with the headers.
