### PR TITLE
Verifying that username exists before auditing in OIDC

### LINKED ISSUE #887: audit event doesn't crash when no username is displayed

### PR DESCRIPTION
**Pull request by orenbm**
#### What does this PR do?
fixes a bug in which the user got an indiscriptive exception of nul pointer rather than the real problem. This happens  when we have an exception before we get the username from the OIDC provider.

#### What ticket does this PR close?
closes #887 

#### Where should the reviewer start?
oidc-login
oidc-authenticate

#### How should this be manually tested?
Run oidc flow with an invalid grant and verify the message says that

### CODE REVIEW

File: spec/app/domain/authentication/authn-oidc/oidc_spec.rb [hunk 1]
```diff
@@ -224,5 +271,35 @@
                               )
       end
     end
+
+    context "that receives authenticate request" do
```
Comment (jtuttle) [inline spec/app/domain/authentication/authn-oidc/oidc_spec.rb]: Could you jsut add `"and fails on oidc details retrieval"` to the end of this description to be consistent with the one above?
