### PR TITLE
Fixed delimiter validation in resources endpoint

### LINKED ISSUE #1997: Offset accepts string as valid input
## Summary
Our REST API for list, accepts a string for `offset` as valid data when it should only accept a numeric value. When we run `offset=somestring`, we get the JSON data from the Conjur server without any constraints applied to it as if we were to run `conjur list`

For example, the returned data would resemble the following
```
      {
        "version": 2166,
        "created_at": "2021-01-14T09:31:31.605+00:00",
        "policy_text": "- !layer somelayer\n- !group somegroup\n- !host anotherhost\n- !user someuser\n- !variable 
...
        "client_ip": "54.236.50.115",
        "id": "cucumber:policy:root",
        "role": "cucumber:user:admin"
      },
```

## Steps to Reproduce
1. Run
```
curl -k -H "$(conjur authn authenticate -H)" \
   'https://conjur-server/resources/cucumber?offset=somestring' \
     | jq .
```

## Expected Results
A non-numeric value for `offset` should return a 500 internal server error like `limit` does

## Actual Results (including error logs, if applicable)
```
...
      {
        "version": 2166,
        "created_at": "2021-01-14T09:31:31.605+00:00",
...
        "finished_at": "2021-01-14T09:31:31.747+00:00",
        "client_ip": "54.236.50.115",
        "id": "cucumber:policy:root",
        "role": "cucumber:user:admin"
      },
...
```
## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
All versions

## Environment setup
DAP server in AWS, Conjur CLI on my local machine

## Additional Information
NA

### PR DESCRIPTION
**Pull request by liavyona**
### What does this PR do?
- _What's changed? Added delimiter validation to `resources` endpoint
- _Are there relevant screenshots you can add to the PR description?_
image

image

### What ticket does this PR close?
Resolves #1997

#### Change log
- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [x] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

### CODE REVIEW

File: app/models/resource.rb [hunk 1]
```diff
@@ -105,6 +105,9 @@ def search account: nil, kind: nil, owner: nil, offset: nil, limit: nil, search:
       scope = scope.textsearch(search) if search
 
       if offset || limit
+        if (offset && !numeric?(offset)) || (limit && !numeric?(limit))
+          raise ApplicationController::UnprocessableEntity, "Delimiter must be an integer if given"
```
Comment (orenbm) [inline app/models/resource.rb:109]: @shulifink can you please review this message?

**Review by orenbm — APPROVED** [review]
LGTM @liavyona , thanks! 
please get a review from @shulifink on the message.

**Comment by izgeri** [comment]
@liavyona please make sure to add a change log message for this! it's definitely a user-impacting change, and we should let people know we've fixed this.

**Comment by orenbm** [comment]
@liavyona the code is fine by me but i would like to see a better commit message. please read [this post](https://chris.beams.io/posts/git-commit/). To be specific, please change the tense to `Fix` instead of `Fixed` and add a description that will explain this change a bit better for the future devs who will see it.

File: CHANGELOG.md [hunk 2]
```diff
@@ -24,6 +24,9 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - Requests with empty body and application/json Content-Type Header will now
   return 400 error instead of 500 error.
   [cyberark/conjur#1968](https://github.com/cyberark/conjur/issues/1968)
+- `resources` requests with non numeric delimiter (limit or offset) will now
```
Comment (sigalsax) [inline CHANGELOG.md:27]: it is more than that. Your change will not count non numeric input as valid input because before offset=somestring returned a whole list previously

File: app/models/resource.rb [hunk 3]
```diff
@@ -105,6 +105,12 @@ def search account: nil, kind: nil, owner: nil, offset: nil, limit: nil, search:
       scope = scope.textsearch(search) if search
 
       if offset || limit
+        if limit && !numeric?(limit)
+          raise ApplicationController::UnprocessableEntity, "'limit' contains an invalid value. Limit must be an integer greater than 0."
+        end
+        if offset && !numeric?(offset)
+          raise ApplicationController::UnprocessableEntity, "'offset' contains an invalid value. Offset must be an integer."
```
Comment (sigalsax) [inline app/models/resource.rb:112]: why isn't this also "must be an integer greater than 0"? Is offset -3 valid and should we accept that?

File: app/models/resource.rb [hunk 4]
```diff
@@ -105,6 +105,14 @@ def search account: nil, kind: nil, owner: nil, offset: nil, limit: nil, search:
       scope = scope.textsearch(search) if search
 
       if offset || limit
+        # 'limit' must be an integer greater than 0 if given
+        if limit && (!numeric?(limit) || limit.to_i <= 0)
+          raise ApplicationController::UnprocessableEntity, "'limit' contains an invalid value. Limit must be an integer greater than 0."
+        end
+        # 'offset' must be an integer greater than or equal to 0 if given
+        if offset && (!numeric?(offset) || offset.to_i < 0)
```
[the remark this answers is not in the document]
Comment (sigalsax) [reply app/models/resource.rb:113]: @liavyona what about this recommendation?

**Review by sigalsax — APPROVED** [review]
Great work! Thanks for jumping on this bug
A couple of things 1. as Oren mentioned please check with Shuli that these logs are ok before merging 2. I tagged you in a codeclimate suggestion so check that out :)

File: app/models/resource.rb (hunk 1 above)
Comment (shulifink) [reply app/models/resource.rb]: I don't understand. What do you mean "if given"?

Comment (shulifink) [reply app/models/resource.rb]: @liavyona Isn't it enough to just say "If you provide a value for Delimiter, it must be an integer greater than or equal to 0".

or simply: "Delimiter must be an integer greater than or equal to 0".

or  "... must be an integer", or "must be a positive integer " (depending on what the integer type)

**Review by shulifink — CHANGES_REQUESTED** [review]

**Review by sigalsax — DISMISSED** [review]
LGTM! Thanks for this improvement!

File: app/models/resource.rb [hunk 5]
```diff
@@ -105,6 +104,14 @@ def search account: nil, kind: nil, owner: nil, offset: nil, limit: nil, search:
...
 
       if offset || limit
+        # 'limit' must be an integer greater than 0 if given
+        if limit && (!numeric?(limit) || limit.to_i <= 0)
+          raise ApplicationController::UnprocessableEntity, "'limit' contains an invalid value. 'limit' must be a positive integer."
+        end
+        # 'offset' must be an integer greater than or equal to 0 if given
+        if offset && (!numeric?(offset) || offset.to_i.negative?)
+          raise ApplicationController::UnprocessableEntity, "'offset' contains an invalid value. 'offset' must be an integer greater than or equal to 0."
+        end
```
Comment (jonahx) [inline app/models/resource.rb:114]: `UnprocessableEntity` is an http level concern.  That is, we should only be talking about that error inside of controllers, and specifically in code that is mapping an actual domain error into an http status code.

Inside of the model we should be raising a more specific validation error, with a name that reflects what went wrong.  `InvalidQueryParameter` or something like that.

Separate comment: There's a lot of formatting / clean changes here (which is awesome), but please put those into a separate commit with a subject like "Cleanup formatting" -- otherwise the "meat" of this PR (which is actually pretty small and simple) isn't clear at a glance.

Comment (liavyona) [reply app/models/resource.rb:114]: We handle the `UnprocessableEntity` with rendering the response. I think this a redundant addition.

Comment (liavyona) [reply app/models/resource.rb:114]: About the formatting I agree. But I think that since it is a very small PR (both logic and formatting) the separation here is not mandatory.
Is it a blocker? @jonahx

Comment (liavyona) [reply app/models/resource.rb:115]: @jonahx fixed

**Review by jonahx — DISMISSED** [review]

**Review by InbalZilberman — COMMENTED** [review]
Looks great @liavyona 
Thank you for taking this on.

File: app/controllers/resources_controller.rb [hunk 6]
```diff
@@ -19,7 +19,13 @@ def index
     # The v5 API currently sends +acting_as+ when listing resources
     # for a role other than the current user.
     query_role = params[:role].presence || params[:acting_as].presence
-    scope = Resource.visible_to(assumed_role(query_role)).search options
+    begin
+        scope = Resource.visible_to(assumed_role(query_role)).search options
+    rescue ApplicationController::Forbidden => e
+      raise e
```
Comment (orenbm) [inline app/controllers/resources_controller.rb:25]: this can also be
```
rescue ApplicationController::Forbidden
  raise
```

File: app/models/resource.rb [hunk 7]
```diff
@@ -2,43 +2,43 @@
...
       end
-      response["permissions"] = permissions.as_json.map {|h| h.except 'resource'}
-      response["annotations"] = self.annotations.as_json.map {|h| h.except 'resource'}
+      response["permissions"] = permissions.as_json.map { |h| h.except 'resource' }
+      response["annotations"] = self.annotations.as_json.map { |h| h.except 'resource' }
       case kind
       when "variable"
         response["secrets"] = secrets_dataset.order(:version).as_json
-          .map { |h| h.except 'resource' }
+                                             .map { |h| h.except 'resource' }
```
Comment (orenbm) [inline app/models/resource.rb:37]: can you fix all the non-code changes that you made to this file?

File: app/models/resource.rb [hunk 8]
```diff
@@ -105,6 +105,14 @@ def search account: nil, kind: nil, owner: nil, offset: nil, limit: nil, search:
       scope = scope.textsearch(search) if search
 
       if offset || limit
+        # 'limit' must be an integer greater than 0 if given
+        if limit && (!numeric?(limit) || limit.to_i <= 0)
+          raise "'limit' contains an invalid value. 'limit' must be a positive integer."
+        end
+        # 'offset' must be an integer greater than or equal to 0 if given
+        if offset && (!numeric?(offset) || offset.to_i.negative?)
+          raise "'offset' contains an invalid value. 'offset' must be an integer greater than or equal to 0."
```
Comment (orenbm) [inline app/models/resource.rb:114]: @liavyona is it possible to move these errors to `errors.rb`?
we prefer to have all the user-facing messages there

File: cucumber/api/features/resource_list.feature [hunk 9]
```diff
@@ -57,10 +57,42 @@ Feature: List resources with various types of filtering
     When I successfully GET "/resources/cucumber/test-resource?limit=1"
     Then I receive 1 resources
 
+  Scenario: The resource list cannot be limited with non numeric value
+    When I GET "/resources/cucumber/test-resource?limit=abc"
+    Then the HTTP response status code is 422
```
Comment (orenbm) [inline cucumber/api/features/resource_list.feature:62]: do we want to add also log validation for these tests?

File: app/models/resource.rb (hunk 1 above)
Comment (InbalZilberman) [reply app/models/resource.rb]: I would go with "Delimiter offset or limit must be an integer greater than or equal to 0"

File: app/models/resource.rb (hunk 8 above)
Comment (liavyona) [reply app/models/resource.rb:114]: I think it will be a problem to use a custom exception inside a model class. Ads you can see there is no usage of any error which is defined at `errors.rb` under `app/model`. Other model classes use simple `raise` or `ArgumentError`. I changed it to use `ArgumentError`

File: app/models/resource.rb (hunk 7 above)
Comment (liavyona) [reply app/models/resource.rb:37]: Talked about it

**Review by orenbm — DISMISSED** [review]

**Review by orenbm — APPROVED** [review]
