### PR TITLE
config can be reloaded with conjurctl

### LINKED ISSUE #2171: Config can be reloaded with conjurctl
Add a `conjurctl configuration apply` command that validates configuration by instantiating a `Conjur::ConjurConfig` object. If validation fails, it should print the exception message to sderr and exit with code 1. If validation succeeds, it should restart the puma server using a [phased restart](https://github.com/puma/puma/blob/master/docs/restart.md#phased-restart) using the following steps:

- get the puma process id: `ps -ef | grep puma | grep -v grep | grep -v cluster | awk '{print $2}' | tr -d '\n'`
- send signal w/ `Process.kill('USR1', <pid>)` (see [docs](https://ruby-doc.org/core-2.4.1/Process.html#method-c-kill))

Unit tests
- Success case (not sure how to test this yet)
- Invalid configuration displays message that includes which fields failed validation
- Invalid configuration causes exit w/ code 1
    
Integration tests
- Given a valid trusted proxies configuration, When `conjur configuration apply` is run, Then the correct IP is displayed in an audit event based on the new config

### PR DESCRIPTION
**Pull request by jtuttle**
close #2171

### CODE REVIEW

File: bin/conjur-cli/commands/configuration/apply.rb [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        @output_stream.puts(
+          "Conjur server reboot initiated. New configuration will be applied."
+        )
+      end
+
+      private
+
+      def server_pid
+        cmd = `ps -ef | grep puma | grep -v grep | grep -v cluster | awk '{print $2}' | tr -d '\n'`
+        stdout, _ = @command_runner.capture2(cmd)
```
[the remark this answers is not in the document]
Comment (jtuttle) [reply bin/conjur-cli/commands/configuration/apply.rb:47]: @jonahx Do you agree with this? I would kind of prefer to see an explicit underscore to show there's an unused param.

File: bin/conjur-cli.rb [hunk 2]
```diff
@@ -251,6 +252,19 @@
...
+  cgrp.long_desc(<<~DESC)
+    Performs a phased restart of the puma process, which restarts the worker
+    threads and allows them to pick up any changes to configuration files. Note
+    that this does NOT pick up any changes to environment variables due to Linux
+    process environments being static once a process has started.
+  DESC
+  cgrp.command :apply do |c|
+    c.action do |_global_options, options, _args|
+      Commands::Configuration::Apply.new.call
+    end
```
Comment (jonahx) [inline bin/conjur-cli.rb:266]: Looks like we're not using any of these block parameters -- can we delete them?

File: bin/conjur-cli/commands/configuration/apply.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (jonahx) [reply bin/conjur-cli/commands/configuration/apply.rb:47]: Yes, I agree.  This is rubocop default so we'll need to issue a pull request and create an issue to get it approved now, per `conjur-project-config` protocol.  I don't expect anyone will mind though, so I'm fine approving this and betting on the future change being accepted.

File: bin/conjur-cli/commands/configuration/apply.rb [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+        end
+
+        Process.kill('USR1', pid)
+
+        puts "Conjur server reboot initiated. New configuration will be applied."
+      end
+
+      private
+
+      def server_pid
```
[the remark this answers is not in the document]
Comment (jonahx) [reply bin/conjur-cli/commands/configuration/apply.rb:45]: This could be utility function on some module like `ProcessInfo`, but if we're only ever using it here not worth it to introduce that imo.

File: bin/conjur-cli/commands/configuration/apply.rb [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+        @output_stream.puts(
+          "Conjur server reboot initiated. New configuration will be applied."
+        )
+      end
+
+      private
+
+      def server_pid
+        cmd = "ps -ef | grep puma | grep -v grep | grep -v cluster | awk '{print $2}' | tr -d '\n'"
```
Comment (jonahx) [inline bin/conjur-cli/commands/configuration/apply.rb:46]: break lines.

File: spec/conjurctl/commands/configuration/apply_spec.rb [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+    before do
+      allow(command_runner).to receive(:capture2).and_return("0")
+    end
+
+    it "outputs an error" do
+      expect { apply_cmd.call }.
+        to raise_error(
+             RuntimeError,
+             "Conjur is not currently running, please start it with conjurctl server."
+           )
```
Comment (jonahx) [inline spec/conjurctl/commands/configuration/apply_spec.rb:50]: Formatting suggestion:
```rb
  expect { apply_cmd.call }.to(
    raise_error(
      RuntimeError,
      "Conjur is not currently running, please start it with conjurctl server."
    )
  )
```

File: spec/conjurctl/commands/configuration/apply_spec.rb [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+      expect(process_manager).to receive(:kill).with('USR1', 123)
+      apply_cmd.call
+    end
+
+    it "prints success message" do
+      allow(process_manager).to receive(:kill).with('USR1', 123)
+
+      expect(output_stream).
+        to receive(:puts).
+        with("Conjur server reboot initiated. New configuration will be applied.")
```
Comment (jonahx) [inline spec/conjurctl/commands/configuration/apply_spec.rb:35]: Formatting suggestion:
```rb
expect(output_stream).to receive(:puts).with(
  "Conjur server reboot initiated. New configuration will be applied."
)
```

File: spec/conjurctl/commands/configuration/apply_spec.rb (hunk 5 above)
Comment (jonahx) [reply spec/conjurctl/commands/configuration/apply_spec.rb:50]: Alternative:
```rb
  expect { apply_cmd.call }.to raise_error(
    RuntimeError,
    "Conjur is not currently running, please start it with conjurctl server."
  )
```

File: bin/conjur-cli.rb (hunk 2 above)
Comment (jtuttle) [reply bin/conjur-cli.rb:266]: We will be shortly so going to leave 'em in.

File: bin/conjur-cli/commands/configuration/apply.rb [hunk 7]
```diff
@@ -0,0 +1,34 @@
+# frozen_string_literal: true
+
+require 'command_class'
+require 'conjur/conjur_config'
+
+module Commands
+  module Configuration
```
[the remark this answers is not in the document]
Comment (jonahx) [reply bin/conjur-cli/commands/configuration/apply.rb:8]: Should probably be respecting these ones.

**Review by h-artzi — APPROVED** [review]

**Review by h-artzi — APPROVED** [review]
