### PR TITLE
Fix k8s builds 755

### LINKED ISSUE #755: CI Pipeline fails sporadically on k8s tests
Example failed builds, with different test failures/errors:

https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur/detail/master/468/pipeline
```
Scenario: Authenticate as a Pod.                                # ./cucumber/kubernetes/features/authenticate.feature:3
    Given I login to authn-k8s as "pod/inventory-pod"             # cucumber/kubernetes/features/step_definitions/login_steps.rb:33
    Then I can authenticate with authn-k8s as "pod/inventory-pod" # cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:23
      no implicit conversion of nil into String (TypeError)
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `initialize'
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `new'
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `/^I( can)? authenticate with authn-k8s as "([^"]*)"( without cert and key)?$/'
      ./cucumber/kubernetes/features/authenticate.feature:5:in `Then I can authenticate with authn-k8s as "pod/inventory-pod"'

```

https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur/detail/master/464/pipeline
```
  Scenario: Authenticate as a Deployment.                                       # ./cucumber/kubernetes/features/authenticate.feature:15
    Given I login to authn-k8s as "deployment/inventory-deployment"             # cucumber/kubernetes/features/step_definitions/login_steps.rb:33
    Then I can authenticate with authn-k8s as "deployment/inventory-deployment" # cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:23
      no implicit conversion of nil into String (TypeError)
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `initialize'
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `new'
      ./cucumber/kubernetes/features/step_definitions/authenticate_steps.rb:28:in `/^I( can)? authenticate with authn-k8s as "([^"]*)"( without cert and key)?$/'
      ./cucumber/kubernetes/features/authenticate.feature:17:in `Then I can authenticate with authn-k8s as "deployment/inventory-deployment"'

```

### PR DESCRIPTION
**Pull request by sgnn7**
#### What does this PR do?
Should fix majority of intermittent issues with k8s tests
 
#### What ticket does this PR close?
Closes #755 

#### Where should the reviewer start?
Going through individual commits - the full diff is a bit messy to look otherwise

#### How should this be manually tested?
Rebuild the branch a few times. Ensure that it doesn't break on k8s tests.

#### Link to build in Jenkins (if appropriate)
https://jenkins.conjur.net/job/cyberark--conjur/job/fix-k8s-builds-755/

#### Has the Version and Changelog been updated?
Probably does not need one

Yes - same tests as before, just that these pass.

> Can we make a blog post, video, or animated GIF of this?
Not really

> Has this change been documented (Readme, docs, etc.)?
Doesn't seem to have a need for it

> Does the knowledge base need an update?
No

### CODE REVIEW

File: app/domain/authentication/authn_k8s/inject_client_cert.rb [hunk 1]
```diff
@@ -27,13 +27,17 @@ def validate
...
 
       def install_signed_cert
-        exec = @kubectl_exec.new(
-          pod_name: spiffe_id.name,
-          pod_namespace: spiffe_id.namespace,
-          logger: Rails.logger,
-          kubeclient: @k8s_object_lookup.kubectl_client
+        pod_namespace = spiffe_id.namespace
+        pod_name = spiffe_id.name
+        puts "Copying SSL cert to #{pod_namespace}/#{pod_name}"
```
Comment (jvanderhoof) [inline app/domain/authentication/authn_k8s/inject_client_cert.rb]: What do you think about logging these instead of using `puts`?

Comment (sgnn7) [reply app/domain/authentication/authn_k8s/inject_client_cert.rb]: Hmm... haven't used the logger previously in the way we use it in the project - do we have an example I can compare/copy-paste?

Comment (sgnn7) [reply app/domain/authentication/authn_k8s/inject_client_cert.rb]: Ugh - ignore this - we use it in the other file I worked on lol

Comment (jvanderhoof) [reply app/domain/authentication/authn_k8s/inject_client_cert.rb]: :) it'll at least let us turn the volume up and down.

File: Dockerfile [hunk 2]
```diff
@@ -2,42 +2,41 @@ FROM ubuntu:16.04
...
 
-ADD Gemfile      .
-ADD Gemfile.lock .
+COPY Gemfile \
+     Gemfile.lock ./
 
 RUN bundle --without test development
 
-ADD . .
+COPY . .
```
Comment (jtuttle) [inline Dockerfile]: Are all of the changes to this file just syntax? The only one that looks like it might not be is this line. Is this part of the fix?

File: app/domain/authentication/authn_k8s/kubectl_exec.rb [hunk 3]
```diff
@@ -26,106 +27,68 @@ def channel_names
...
-      def copy(path, content, mode)
-        execute(
-          [ 'tar', 'xvf', '-', '-C', '/' ],
-          stdin: true,
-          body: tar_file_as_string(path, content, mode)
-        )
-      end
-      
+
+      # on_* methods are public since ws_client needs public callbacks that it will
```
Comment (jtuttle) [inline app/domain/authentication/authn_k8s/kubectl_exec.rb]: I think you could remove the `that it will invoke` from this comment to fit it on one line. Why else would it need public callbacks unless it was planning to invoke them. :)

File: app/domain/authentication/authn_k8s/kubectl_exec.rb [hunk 4]
```diff
@@ -153,23 +116,29 @@ def on_message(msg, ws_client)
...
+
+        error_info = err.inspect
+        @logger.debug("Pod #{@pod_name} error : #{error_info}")
+        @message_log.save_error_string(error_info)
       end
 
       private
 
+      def kubeclient
+        @kubeclient ||= @k8s_object_lookup.kubectl_client
```
Comment (jtuttle) [inline app/domain/authentication/authn_k8s/kubectl_exec.rb]: What is `@k8s_object_lookup` resolving to...? I don't see it defined anywhere else in the class.

File: Dockerfile (hunk 2 above)
Comment (sgnn7) [reply Dockerfile]: They're not just syntax, they're a lot are reordering to reduce/reuse cache layers. This particular change though is due to the fact that `ADD` is generally used to put something in the image from a compredded file or the web vs the `COPY` which is an explicit local FS copy.

File: app/domain/authentication/authn_k8s/kubectl_exec.rb (hunk 4 above)
Comment (sgnn7) [reply app/domain/authentication/authn_k8s/kubectl_exec.rb]: It's in the dependencies: https://github.com/cyberark/conjur/blob/3e2b06c183da59a177f6c06c055c8b6bab8001d1/app/domain/authentication/authn_k8s/kubectl_exec.rb#L58
