### PR TITLE
Usable config file validation error

### LINKED ISSUE #2256: Invalid configuration file format produces nice error
If a ConjurConfig object is initialized and tries to read an invalid YAML file, it will currently fail with an uncaught exception:

```
bundler: failed to load command: bin/conjurctl (bin/conjurctl)
/opt/conjur/possum/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.1.0/lib/anyway/utils/deep_merge.rb:8:in `deep_merge!': undefined method `each' for "trusted_proxies":String (NoMethodError)
	from /opt/conjur/possum/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.1.0/lib/.rbnext/2.7/anyway/config.rb:322:in `block in load_from_sources'
	from /opt/conjur/possum/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.1.0/lib/.rbnext/3.0/anyway/loaders.rb:55:in `each'
...
```

Add a ConfigLoader class whose job is it to load the ConjurConfig object and catch this exception and provide a better error message. Use this in the places where we instantiate a ConjurConfig object.

### PR DESCRIPTION
**Pull request by micahlee**
### What does this PR do?

This PR updates the Conjur config file load to output a user-friendly validation error when the config file contains a YAML syntax error, or the root YAML object is not a dictionary. Previously, these errors output a library-internal exception and stack trace.

### What ticket does this PR close?
Resolves #2256

#### Change log
- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [x] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

#### API Changes
- [ ] The [OpenAPI spec](https://github.com/cyberark/conjur-openapi-spec) has been updated to meet new API changes (or an issue has been opened), or
- [x] The changes in this PR do not affect the Conjur API

### CODE REVIEW

File: lib/conjur/conjur_config.rb [hunk 1]
```diff
@@ -26,6 +26,30 @@ class ConjurConfig < Anyway::Config
       authenticators: []
     )
 
+    def initialize(*args)
+      super(*args)
+
+    # If theh config file is not a valid YAML document, we want
```
Comment (jvanderhoof) [inline lib/conjur/conjur_config.rb:32]:
```suggestion
    # If the config file is not a valid YAML document, we want
```

File: lib/conjur/conjur_config.rb [hunk 2]
```diff
@@ -26,6 +26,30 @@ class ConjurConfig < Anyway::Config
...
+
+    # If the config file is valid YAML, but the root object is
+    # not a YAML dictionary, this raises one of a number of
+    # NoMethodError exceptions because AnywayConfig assumes parsing
+    # the config file will result in a Ruby Hash. We capture
+    # this and raise a more user-friendly error message.
+    rescue NoMethodError
+      raise(
+        ConfigValidationError,
+        "Config file is not a valid YAML dictionary."
```
Comment (jtuttle) [inline lib/conjur/conjur_config.rb:49]: It's (probably) possible that a `NoMethodError` can arise for a different reason since it's so generic. Would it make more sense to have an error message that's less certain about the cause? Something like "Unable to parse config file. Please ensure that it is a valid YAML dictionary."

**Review by jtuttle — CHANGES_REQUESTED** [review]

File: lib/conjur/conjur_config.rb (hunk 1 above)
Comment (micahlee) [reply lib/conjur/conjur_config.rb:32]: doh... Thanks!

File: lib/conjur/conjur_config.rb (hunk 2 above)
Comment (micahlee) [reply lib/conjur/conjur_config.rb:49]: Yeah, that makes sense. I'll make the change.

**Review by jtuttle — APPROVED** [review]
